### ISSUE TITLE
On search 

### ISSUE THREAD

**Issue by anixer0** [KiriXen/gogoanime#1]
When I search anime and click the anime l want to watch the episode isn't showing

**Comment by SailorSammyy** [comment]
> When I search anime and click the anime l want to watch the episode isn't showing

Are u hostin it somewhere or just local ?

**Comment by anixer0** [comment]
I'm using hosting

**Comment by anixer0** [comment]
![Screenshot_20240801-195831_2](https://github.com/user-attachments/assets/0001bff9-fbd0-4fa9-81f2-4374d1a0315a)

**Comment by SailorSammyy** [comment]
> ![Screenshot_20240801-195831_2](https://private-user-images.githubusercontent.com/172897096/354213587-0001bff9-fbd0-4fa9-81f2-4374d1a0315a.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjI1NzE5NzIsIm5iZiI6MTcyMjU3MTY3MiwicGF0aCI6Ii8xNzI4OTcwOTYvMzU0MjEzNTg3LTAwMDFiZmY5LWZiZDAtNGZhOS04MWYyLTQzNzRkMWEwMzE1YS5qcGc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwODAyJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDgwMlQwNDA3NTJaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0xODc5OGFhNjZiZGUyOGNiNDI4ZDY0M2FhMzllZWI1ZDdmYjZmODU0ZjRkYTllZjdjNTQ1ZTE2NTU4NzVjYTVmJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.d1cDUd4r3pt05qqxRUwky0QotJWLlzEfm1f2oLqEKdA)

Let me indentify the problem!

**Comment by anixer0** [comment]
Here's the link 
.
.https://animxer.site/category/one-piece

**Comment by MetaHat** [comment]
i am facing same issue

**Comment by SailorSammyy** [comment]
> i am facing same issue

I've fixed the error before, I'll try checking it tmr if I'm free

**Comment by MetaHat** [comment]
I am the owner of a hosting site, so if you'd like to check out your things live, I'll give you free web hosting.

**Comment by MetaHat** [comment]
i fixed it with a temporary solution 
here how it look
![image](https://github.com/user-attachments/assets/0ca34efa-b5b8-4dcb-bbae-302f3fe3d708)
