### ISSUE TITLE
Does this files require any extension or PHP version in cpanel?

### ISSUE THREAD

**Issue by aypedro** [KiriXen/gogoanime#5]
The animes are not loading after I uploaded to file manager and add API, the anime won't load unless I add .php at the end of the url
mysiteurl.com/home doesn't work
mysiteurl.com/home.php works

**Comment by SailorSammyy** [comment]
> The animes are not loading after I uploaded to file manager and add API, the anime won't load unless I add .php at the end of the url mysiteurl.com/home doesn't work mysiteurl.com/home.php works

well its bcuz u didnt allow or add the .htaccess
